# About
objc: true
author: Alfresco
author_url: https://www.alfresco.com
github_url: https://github.com/Alfresco/activiti-ios
readme: README.md

# Generation
module: AlfrescoSDK
umbrella_header: AlfrescoSDK/AlfrescoSDK.h
framework_root: .
exclude: 
  - "CMIS"
  - "build"
theme: apple
hide_documentation_coverage: true
min_acl: public
output: Help
clean: true
skip_undocumented: true
